### ISSUE TITLE
No simple way to rename assets

### ISSUE THREAD

**Issue by eveninglily** [fuseumass/redpandahacks-config#3]
There's no settings to override the names of the files in `assets/images`, so any files meant to replace these (e.g. profile pics, logo) must also follow the names of `PandaLogo.png` and `red-panda-face.jpg`

It'd be nice (possibly in hackathon.yml) to be able to change where these assets are drawn from, so we can rename them.

**Comment by eveninglily** [comment]
Nevermind, I'm blind

**Comment by jwoglom** [comment]
If you come across any other assets that you think should be configurable, please let us know!

Our intent with the configuration submodule system is to make it so that 99.99% of hackathons never need to fork dashboard itself -- all config can happen in the submodule.
